version: '3.7'

services:
  postgresql:
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: jazapp
      POSTGRES_USER: jazapp
      POSTGRES_PASSWORD: jazapp!98
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local